  .then((message) => {
    console.log(message);
  })
  .catch((error) => {
    console.error("Caught an error", error.message);
  });
